modLoader = "javafml" 
loaderVersion = "58" 
license = "MIT Licence"
[[mods]] 
modId = "rockylib" 
version = "1.28.2+1.21.8" 
displayName = "RockyLib" 
#updateJSONURL="https://www.github.com/RockyyyGM/RockyLib-API/updates.json"
#displayURL=""
logoFile = "rockylib.png"
credits = ""
authors = "RockyDev"
description = '''A Library API For The Mods'''
[[dependencies.rockylib]]
modId = "forge" 
mandatory = true 
versionRange = "[58.0.0,)" 
ordering = "NONE"
side = "BOTH"
[[dependencies.rockylib]]
modId = "minecraft"
mandatory = true
versionRange = "1.21.8-1.22"
ordering = "NONE"
side = "BOTH"